kind: Service
apiVersion: v1
metadata:
  name: go-service
  labels:
    app: go-service
spec:
  type: ClusterIP
  selector:
    app: go-service
  ports:
    - name: tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
        version: v1
    spec:
      containers:
        - name: go-service
          image: localhost:32000/go-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERVICE
              value: go-service
